;;; scholia-status-test.el --- Tests for the scholia status dashboard  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Sören Nikolaus

;; Author: Sören Nikolaus <soeren@code17.io>

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'scholia-test-helper)

(let ((load-prefer-newer t))
  (require 'scholia-vars nil t)
  (require 'scholia-db nil t)
  (require 'scholia-session nil t)
  (require 'scholia-export nil t)
  (require 'scholia-search nil t)
  (require 'scholia-thread nil t)
  (require 'scholia-filter nil t))

(defun scholia-status-test--annotation (id text &optional reply-to)
  "Return annotation ID carrying TEXT and optionally replying to REPLY-TO."
  (list :id id
        :beg (unless reply-to 1) :end (unless reply-to 5)
        :text text :annotated-text (unless reply-to "text")
        :line (unless reply-to 1) :line-text (unless reply-to "text")
        :column (unless reply-to 0) :end-column (unless reply-to 4)
        :color 0 :position :margin :reply-to reply-to :sends nil))

(ert-deftest scholia-status-01-renders-filtered-threaded-sections ()
  (require 'scholia)
  (should-not (featurep 'scholia-status))
  (require 'scholia-status)
  (let* ((root (scholia-status-test--annotation "root" "keep root"))
         (reply (scholia-status-test--annotation "reply" "keep reply" "root"))
         (hidden (scholia-status-test--annotation "hidden" "drop this"))
         (candidates (list (list :session "alpha" :file "/tmp/one.el" :annotation root)
                           (list :session "alpha" :file "/tmp/one.el" :annotation reply)
                           (list :session "beta" :file "/tmp/two.el" :annotation hidden)))
         (filtered (seq-take candidates 2))
         (received nil)
         (walked nil))
    (cl-letf (((symbol-function 'scholia-search-annotations)
               (lambda () candidates))
              ((symbol-function 'scholia-filter-parse)
               (lambda (query) (setq received query) '(text . "keep")))
              ((symbol-function 'scholia-filter-apply)
               (lambda (_filter input)
                 (should (equal input candidates))
                 filtered))
              ((symbol-function 'scholia-thread-walk)
               (lambda (annotations function)
                 (setq walked annotations)
                 (list (funcall function root 0)
                       (funcall function reply 1)))))
      (let ((buffer (scholia-status)))
        (with-current-buffer buffer
          (should (string-match-p "keep root" (buffer-string)))
          (goto-char (point-min))
          (search-forward "keep root")
          (let ((section (magit-current-section)))
            (should (equal (magit-section-value section) root))
            (should (equal (magit-section-value (magit-section-parent section))
                           "/tmp/one.el"))
            (should (equal (magit-section-value
                            (magit-section-parent
                             (magit-section-parent section)))
                           "alpha")))))
      (let ((buffer (scholia-status-filter "text:keep")))
        (should (equal received "text:keep"))
        (should (equal walked (list root reply)))
        (with-current-buffer buffer
          (should (string-match-p "keep root" (buffer-string)))
          (should (string-match-p "keep reply" (buffer-string)))
          (should-not (string-match-p "drop this" (buffer-string)))
          (goto-char (point-min))
          (search-forward "keep reply")
          (let ((section (magit-current-section)))
            (should (equal (magit-section-value section) reply))
            (should (equal (magit-section-value (magit-section-parent section))
                           "/tmp/one.el"))
            (should (equal (magit-section-value
                            (magit-section-parent
                             (magit-section-parent section)))
                           "alpha"))))))))

(ert-deftest scholia-status-02-dispatches-marked-session-actions ()
  (require 'scholia-status)
  (let ((switched nil)
        (renamed nil)
        (exports nil))
    (cl-letf (((symbol-function 'scholia-session-switch)
               (lambda (name) (setq switched name)))
              ((symbol-function 'scholia-session-rename)
               (lambda (old new) (setq renamed (list old new))) )
              ((symbol-function 'scholia-export-session)
               (lambda (sessions &rest _) (push sessions exports))))
      (scholia-status-switch-session "review")
      (scholia-status-rename-session "review" "ready")
      (scholia-status-mark-session "ready")
      (scholia-status-mark-session "archive")
      (scholia-status-export-marked-sessions)
      (should (equal switched "review"))
      (should (equal renamed '("review" "ready")))
      (should (equal exports '(("ready" "archive")))))))

(ert-deftest scholia-status-03-jumps-histories-and-deletes-orphans ()
  (require 'scholia-status)
  (scholia-test-with-session-directory
    (let* ((file "/tmp/status-orphan.el")
           (session (scholia-session-file "review"))
           (kept (scholia-status-test--annotation "kept" "still here"))
           (orphan (scholia-status-test--annotation "orphan" "lost reply" "gone"))
           (record (scholia-db-make-record file (list kept orphan) "seed"))
           (entry (list :session "review" :record record :annotation orphan))
           (jumped nil)
           (history nil))
      (scholia-db-create-session session)
      (scholia-db-store-record session record)
      (cl-letf (((symbol-function 'scholia-search--jump)
                 (lambda (value) (setq jumped value)))
                ((symbol-function 'scholia-search-sends)
                 (lambda () (setq history t))))
        (scholia-status-jump entry)
        (scholia-status-show-send-history entry)
        (should (eq jumped entry))
        (should history))
      (scholia-status-delete entry)
      (should (equal (mapcar #'scholia-db-annotation-id
                             (scholia-db-record-annotations
                              (scholia-db-record session file)))
                     '("kept"))))))

(ert-deftest scholia-status-04-sends-selected-hunks-as-one-batch ()
  (require 'scholia-status)
  (scholia-test-with-session-directory
    (let* ((file "/tmp/status-send.el")
           (session (scholia-session-file "review"))
           (first (scholia-status-test--annotation "one" "first hunk"))
           (second (scholia-status-test--annotation "two" "second hunk"))
           (selected (list (list :session "review" :file file :annotation first)
                           (list :session "review" :file file :annotation second)))
           (entry '(agent . "target"))
           (entries 0)
           (renders nil)
           (sends nil))
      (scholia-db-create-session session)
      (scholia-db-store-record
       session (scholia-db-make-record file (list first second) "seed"))
      (cl-letf (((symbol-function 'scholia-herdr--entry)
                 (lambda () (setq entries (1+ entries)) entry))
                ((symbol-function 'scholia-export-render)
                 (lambda (annotations &rest _)
                   (push annotations renders)
                   "first hunk\nsecond hunk"))
                ((symbol-function 'scholia-herdr--send)
                 (lambda (annotations payload format scope persist)
                   (let* ((target (scholia-herdr--entry))
                          (send (scholia-db-make-send
                                 :kind (car target) :target (cdr target)
                                 :label "agent · target" :format format :scope scope)))
                     (push (list annotations payload format scope target) sends)
                     (funcall persist
                              (mapcar (lambda (annotation)
                                        (scholia-db-annotation-add-send annotation send))
                                      annotations)
                              send)))))
        (scholia-status-send selected)
        (should (= entries 1))
        (should (equal renders (list (list first second))))
        (should (= (length sends) 1))
        (should (equal (car (car sends)) (list first second)))
        (should (equal (nth 1 (car sends)) "first hunk\nsecond hunk"))
        (let ((stored (scholia-db-record session file)))
          (should (equal (mapcar #'scholia-db-annotation-id
                                 (scholia-db-record-annotations stored))
                         '("one" "two")))
          (should (equal
                   (mapcar (lambda (annotation)
                             (mapcar #'scholia-db-send-target
                                     (scholia-db-annotation-sends annotation)))
                           (scholia-db-record-annotations stored))
                   '(("target") ("target")))))))))

(provide 'scholia-status-test)
;;; scholia-status-test.el ends here
